---
kind: pipeline
type: docker
name: test_python-3-9

steps:
  - name: run tests
    image: mwalbeck/python-poetry:1.2-3.9
    environment:
      APP_DIR: determine_docker_tags
      POETRY_VIRTUALENVS_CREATE: "false"
    commands:
      - poetry install
      - black --check $${APP_DIR}
      - flake8 $${APP_DIR}
      - pytest

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: test_python-3-10

steps:
  - name: run tests
    image: mwalbeck/python-poetry:1.2-3.10
    environment:
      APP_DIR: determine_docker_tags
      POETRY_VIRTUALENVS_CREATE: "false"
    commands:
      - poetry install
      - black --check $${APP_DIR}
      - flake8 $${APP_DIR}
      - pytest

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: release

steps:
  - name: release new version
    image: mwalbeck/python-poetry:1.2-3.10
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - poetry install
      - poetry publish --build

trigger:
  event:
    - tag

---
kind: signature
hmac: 3494f82b6e37802cf4f074ec00fc5ffbc88d84a49a3c2d8fbe0c24b0f329df5b

...
