name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies, build, and publish - Forgejo
        env:
          POETRY_REPOSITORIES_FORGEJO_URL: https://git.walbeck.it/api/packages/walbeck-it/pypi
          POETRY_HTTP_BASIC_FORGEJO_USERNAME: ${{ secrets.FORGEJO_PACKAGES_USERNAME }}
          POETRY_HTTP_BASIC_FORGEJO_PASSWORD: ${{ secrets.FORGEJO_PACKAGES_TOKEN }}
        run: |
          poetry install
          poetry publish --build --repository forgejo
          
      - name: Install dependencies, build, and publish - PyPi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish

  docker:
    runs-on: dind
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "string"
          STRING_VERSION: ${{ forgejo.ref_name }}
          CUSTOM_TAGS: "latest"
          IMAGE_NAME: "mwalbeck/determine-docker-tags"
        run: |
          determine-docker-tags
          
      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "string"
          STRING_VERSION: ${{ forgejo.ref_name }}
          CUSTOM_TAGS: "latest"
          IMAGE_NAME: "git.walbeck.it/walbeck-it/determine-docker-tags"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: actions/docker-login@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: actions/docker-login@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: actions/docker-setup-buildx@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build and push
        uses: actions/docker-build-push@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: true
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}
